version: '3.3'

services:
  db:
    image: postgres:9.6.10-alpine
    environment:
      POSTGRES_USER: phoenix
      POSTGRES_PASSWORD: phoenix
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - /var/data/postgresql:/var/lib/postgresql/data

  phoenix:
    image: jesk/realworld:1.0
    environment:
      DB_USER: "phoenix"
      DB_PASSWORD: "phoenix"
      DB_NAME: "phoenix"
      DB_HOST: "db"
      DB_PORT: "5432"
      PORT: "4000"
      MIX_ENV: "dev"
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: host
    depends_on:
      - db
