apiVersion: v1
kind: ResourceQuota
metadata:
  name: real-world-rquota
  namespace: real-world
spec:
  hard:
    requests.cpu: "4000m"
    requests.memory: "2Gi"
    limits.cpu: "2000m"
    limits.memory: "512Mi"
    pods: "6"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: real-world
spec:
  limits:
  - default:
      cpu: "2000m"
      memory: "512Mi"
    defaultRequest:
      cpu: "500m"
      memory: "128Mi"
    type: Container
